### PR TITLE
Fix the constructor import issue (2)

### LINKED ISSUE #1282: FFI Constructor Import Issue
This issue is related and similar to #1123 .

When generating Haskell bindings for C libraries using hs-bindgen, compilation fails with errors about missing newtype constructors in FFI declarations when types wrap external types from other modules.

GHC's FFI marshalling requires that when a newtype is used in a foreign import
declaration, all constructors in the entire newtype chain must be in scope.
For example:

1. Module RPM.Types defines:

```hs
newtype RpmFlags = RpmFlags { un_RpmFlags :: Word32 }
```

2. Module RPM.Argv defines:

```hs
import qualified RPM.Types

newtype ArgvFlags = ArgvFlags { un_ArgvFlags :: RPM.Types.RpmFlags }
```

3. Module RPM.Argv.Unsafe uses ArgvFlags in FFI:

```hs
import RPM.Argv
foreign import ccall unsafe "..." argvSplitString :: ... -> ArgvFlags -> IO
 ...
```

The issue: RPM.Argv.Unsafe has ArgvFlags(..) in scope, but not RpmFlags(..).

Haskell imports are not transitive:

- `RPM.Argv` imports `RPM.Types qualified`
- `RPM.Argv.Unsafe` imports `RPM.Argv`
- But `RPM.Argv.Unsafe` does _not_ get `RpmFlags(..)` transitively

One possible solution is to create export lists that make sure the necessary
constructors are re-exported, however this doesn't work because the following
is still possible:

When C bindings reuse the same identifier across different headers, we may
generate:

```hs
module RPM.Ds where
import qualified RPM.Types

newtype RpmRC = RpmRC { un_RpmRC :: RPM.Types.RpmRC }
```

To satisfy FFI requirements, we'd need:

```hs
module RPM.Ds (
    RpmRC(..)           -- Local type
  , RPM.Types.RpmRC(..) -- Underlying type
  ) where
```

However, this creates a name conflict: both exports introduce the constructor
`RpmRC` into the importing module's namespace, causing GHC to reject the export
list.

### PR DESCRIPTION
**Pull request by jorisdral**
Resolves #1282

### CODE REVIEW

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs [hunk 1]
```diff
@@ -1,59 +1,440 @@
...
-foreignImportDec name result parameters origName callConv origin safety =
-    Hs.DeclForeignImport foreignImportDecl
+  -> [Hs.Decl]
+foreignImportDec transState name params res origName callConv origin safety
+  | willForeignImportTypecheck transState funType
+  = [ Hs.DeclForeignImport foreignImportDecl
+    , Hs.DeclFunction funDecl
+    ]
+  | otherwise
+  = panicPure "foreignImportDec: generated binding would not compile"
```
Comment (jorisdral) [inline hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:71]: It's currently a panic regardless of the reason why type checking would fail. There are a few reasons why type checking would fail:

1. `hs-bindgen` has a bug, where it tries to generate a foreign import for an invalid type (such as a Haskell `data` type)
2. In an external binding spec, an `ffitype` was erroneously omitted
3. In an external binding spec, a `HasBaseForeignType` instance was erroneously omitted

Reason 1 should be a panic, reasons 2 and 3 should be caught in the fronted, so that we can emit a warning message and omit the generated bindings.

And we should take the same approach for functions `foreignImportWrapperDec` and `foreignImportDynamicDec`

If we decide to make this change, I'd prefer to do it in a follow-up PR

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs [hunk 2]
```diff
@@ -1,59 +1,440 @@
...
+unsafeToBase ntMap ty = case toBase ntMap ty of
+    Nothing ->
+      panicPure $ printf "Type does not have base foreign type: %s" (show ty)
+    Just ty' ->
+      ty'
+
+toBase :: NewtypeMap -> HsType -> Maybe HsType
+toBase ntMap ty =
+      fmap fromBaseForeignType
+    $ toBaseForeignType ntMap ty
```
Comment (jorisdral) [inline hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:300]: Maybe `ForeignImportDecl`, `ForeignImportWrapper`, and `ForeignImportDynamic` should use `BFT.BaseForeignType` rather than `HsType`? It would require some (boring) plumbing, but the upside would be that we enforce statically that a foreign import declaration only uses base foreign types 

If we decide to make this change, I'd prefer to do it in a follow-up PR

File: examples/constructor-import-issue/c/constructor_import_issue.h [hunk 3]
```diff
@@ -0,0 +1,11 @@
+typedef char A;
+
+typedef A B;
+
+extern B ex_global;
+
+extern B ex_func (B x);
```
Comment (jorisdral) [inline examples/constructor-import-issue/c/constructor_import_issue.h]:
```
foreign import "ex_func" ... :: B -> IO B
```

```
foreign import "ex_func" hs_bindgen_29812748_base :: CChar -> IO CChar

hs_bindgen_29812748  :: B -> IO B
hs_bindgen_29812748 = fromBaseForeignType hs_bindgen_29812748_base

ex_func :: B -> IO B
ex_func = hs_bindgen_29812748
```

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs [hunk 4]
```diff
@@ -1,59 +1,440 @@
...
         , origName   = origName
         , callConv   = callConv
         , origin     = origin
-        , comment    = mbUniqueSymbol
+        , comment    = fiComment
         , safety     = safety
         }
+      where
+
+    fiName = Hs.InternalName (name.uniqSymbol & #unique %~ (<> "_base"))
```
Comment (jorisdral) [inline hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:90]: Add a comment that this name is also unique because it is created from a unique name + suffix

File: examples/constructor-import-issue/c/constructor_import_issue.h
Comment (jorisdral) [inline examples/constructor-import-issue/c/constructor_import_issue.h:1]: We should explain with comments which declarations live in which module/external binding spec

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs [hunk 5]
```diff
@@ -1,59 +1,440 @@
...
   -> Safety
-  -> Hs.Decl
-foreignImportDec name result parameters origName callConv origin safety =
-    Hs.DeclForeignImport foreignImportDecl
+  -> [Hs.Decl]
+foreignImportDec transState name params res origName callConv origin safety
+  | willForeignImportTypecheck transState funType
+  = [ Hs.DeclForeignImport foreignImportDecl
+    , Hs.DeclFunction funDecl
+    ]
```
Comment (jorisdral) [inline hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:69]: This generates two declarations even if the type signatures are exactly the same. Maybe we should run a simplifier pass to "squash" the two when applicable? Let's open a ticket for this

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 1 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:71]: We should open a ticket for the follow-up work

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 2 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:300]: We're probably not going to do this now, so I won't open an issue, but I'll leave a note here for possible improvements in the future

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 1 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:71]: Created an issue: #1566

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 5 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:69]: Opened an issue: #1567

File: examples/constructor-import-issue/c/constructor_import_issue.h
Comment (jorisdral) [reply examples/constructor-import-issue/c/constructor_import_issue.h:1]: Done

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 4 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:90]: Done

File: hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs (hunk 2 above)
Comment (jorisdral) [reply hs-bindgen/src-internal/HsBindgen/Backend/Hs/Translation/ForeignImport.hs:300]: Done
