### PR TITLE
Fix evaluation of error traces

### LINKED ISSUE #1197: Exit code is zero, even with Error traces
I think we defeated our own failure mechanism by using references to cached computations and running them later than expected. I get exit code `0` although I have error traces.

```console
$ cabal run -- hs-bindgen-cli preprocess --hs-output-dir unused not-found
Configuration is affected by the following files:
- cabal.project
[Warning] [HsBindgen] [unique-id] empty unique identifier ('UniqueId'):
  C uses a global namespace.
  We encourage using a unique identifier to avoid duplicate symbol names.
  For example, use and adapt 'com.example.package'.
[Error  ] [Libclang ] [clang] unable to resolve #include <not-found>
[1] 11:19:26 dominik@schwarzbaer:/home/dominik/work/hs-bindgen

$ echo $?
0
```

I think we return from the frontend before running the computations, and so, there are not `Error` traces, yet.

I expect our program fails when we trace to files, the handles will be closed before the traces are emitted.

As far as I understand we are anyways moving towards not failing, even when there was an error; instead we just omit the affected declarations.

### PR DESCRIPTION
**Pull request by bolt12**
This PR fixes #1197

### CODE REVIEW

File: hs-bindgen/src-internal/HsBindgen/Util/Tracer.hs [hunk 1]
```diff
@@ -31,8 +31,10 @@ module HsBindgen.Util.Tracer (
   , TracerConfig (..)
     -- * Tracers
   , withTracer
+  , withTracerRef
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen/Util/Tracer.hs]: Can we replace `withTracer` by `withTracerRef`? I.e., only export one function doing the right thing?

File: hs-bindgen/src-internal/HsBindgen/Util/Tracer.hs [hunk 2]
```diff
@@ -31,8 +31,10 @@ module HsBindgen.Util.Tracer (
...
   , TracerState(..)
   , withTracer'
+  , withTracerRef'
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen/Util/Tracer.hs]: Also here. I think this needs some adaptation in the test suite, but should otherwise be fine.

File: hs-bindgen/src-internal/HsBindgen/Artefact.hs [hunk 3]
```diff
@@ -107,32 +110,44 @@ runArtefacts
...
-
-    runArtefact :: Artefact a -> ArtefactM a
+    go :: Artefacts x -> ArtefactM (Either (TraceException msg) (NP I x))
+    go Nil       = pure (Right Nil)
+    go (a :* as) = do
+      artefactResult <- runArtefact a
+      case artefactResult of
+        Left errors -> pure (Left errors)
+        Right artefact -> do
+          tracerState <- liftIO $ readIORef tracerStateRef
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen/Artefact.hs]: Can we instead export a function from `Tracer.hs` performing this check, and only use this function here? `runArtefacts` does not need to know how to detect an error, only that an error has happend (with a list of error traces I guess).

Comment (dschrempf) [reply hs-bindgen/src-internal/HsBindgen/Artefact.hs]: I guess we will also need the function when adapting the tests.

File: hs-bindgen/src-internal/HsBindgen/Artefact.hs [hunk 4]
```diff
@@ -107,32 +110,44 @@ runArtefacts
...
+          case tracerState of
+            TracerState Error errors -> pure (Left (TraceException errors))
+            _ -> do
+              results <- go as
+              case results of
+                Left err -> pure (Left err)
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen/Artefact.hs]: You could move the `pure` before the `case`, if you want.

Comment (dschrempf) [reply hs-bindgen/src-internal/HsBindgen/Artefact.hs]: It is then maybe better to use `fmap` to handle the `Right` case (but that's a detail).

File: hs-bindgen/src-internal/HsBindgen.hs [hunk 5]
```diff
@@ -73,14 +74,14 @@ hsBindgen
...
-    backendArtefact <- withTracerSafe tracerConfigSafe $ \tracer -> do
-      backend tracer bindgenBackendConfig bootArtefact frontendArtefact
-    -- 4. Artefacts.
-    withTracerSafe tracerConfigSafe $ \tracer -> do
-      runArtefacts tracer bootArtefact frontendArtefact backendArtefact artefacts
+      -- 3. Backend.
+      backendArtefact <- withTracerSafe tracerConfigSafe $ \tracer' -> do
+        backend tracer' bindgenBackendConfig bootArtefact frontendArtefact
+      -- 4. Artefacts.
+      withTracerSafe tracerConfigSafe $ \tracer' -> do
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen.hs]: Yes, I agree. It is suboptimal that we have the safe trace intertwined here. This makes me think we should probably combine the two. Edsko and I thought about this quite a lot, and the beauty of the current approach is that the backend truly only can omit safe traces. On the other hand, I am pretty sure we can lift safe traces into the other tracers at this stage too.

File: hs-bindgen/src-internal/HsBindgen/Artefact.hs [hunk 6]
```diff
@@ -107,32 +110,39 @@ runArtefacts
...
-      FinalModules        -> liftIO backendFinalModules
+      HsDecls             -> Right <$> liftIO backendHsDecls
+      FinalDecls          -> Right <$> liftIO backendFinalDecls
+      FinalModuleBaseName -> pure (Right backendFinalModuleBaseName)
+      FinalModuleSafe     -> Right <$> liftIO backendFinalModuleSafe
+      FinalModuleUnsafe   -> Right <$> liftIO backendFinalModuleUnsafe
+      FinalModules        -> Right <$> liftIO backendFinalModules
       -- Lift and sequence.
-      (Lift as' f)        -> go as' >>= f
+      (Lift as' f)        -> go as' >>= \x -> mapM f x
```
Comment (dschrempf) [inline hs-bindgen/src-internal/HsBindgen/Artefact.hs]:
```suggestion
      (Lift as' f)        -> go as' >>= mapM f
```
