### PR TITLE
Fix redundant import of GHC.Ptr

### LINKED ISSUE #1064: hs-bindgen generates redundant imports
When running the manual, hs-bindgen generates bindings with redundant imports:

```
[1 of 4] Compiling Vector           ( generated/Vector.hs, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-vector-0.1.0/build/Vector.o, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-vector-0.1.0/build/Vector.dyn_o ) [Source file changed]
generated/Game/State.hs:9:1: warning: [GHC-66111] [-Wunused-imports]
    The qualified import of ‘GHC.Ptr’ is redundant
      except perhaps to import instances from ‘GHC.Ptr’
    To import instances alone, use: import GHC.Ptr()
  |
9 | import qualified GHC.Ptr as F
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[2 of 3] Compiling Game.Player      ( generated/Game/Player.hs, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-game-0.1.0/build/Game/Player.o, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-game-0.1.0/build/Game/Player.dyn_o ) [Source file changed]
generated/Vector.hs:11:1: warning: [GHC-66111] [-Wunused-imports]
    The qualified import of ‘GHC.Ptr’ is redundant
      except perhaps to import instances from ‘GHC.Ptr’
    To import instances alone, use: import GHC.Ptr()
   |
11 | import qualified GHC.Ptr as F
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[3 of 3] Compiling Game.World       ( generated/Game/World.hs, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-game-0.1.0/build/Game/World.o, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-game-0.1.0/build/Game/World.dyn_o ) [Source file changed]
[2 of 4] Compiling Vector.Length    ( generated/Vector/Length.hs, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-vector-0.1.0/build/Vector/Length.o, /home/bolt/Desktop/Bolt/UMinho/Profissional/Well-Typed/Projects/hs-bindgen/manual/hs/dist-newstyle/build/x86_64-linux/ghc-9.12.2/hs-vector-0.1.0/build/Vector/Length.dyn_o ) [Source file changed]
generated/Vector/Length.hs:12:1: warning: [GHC-66111] [-Wunused-imports]
    The qualified import of ‘GHC.Ptr’ is redundant
      except perhaps to import instances from ‘GHC.Ptr’
    To import instances alone, use: import GHC.Ptr()
   |
12 | import qualified GHC.Ptr as F
```

### PR DESCRIPTION
**Pull request by dschrempf**
Closes #1064

### CODE REVIEW

**Comment by dschrempf** [comment]
Putting this on the queue since it is a tiny bugfix.

File: hs-bindgen/src-internal/HsBindgen/Backend/Artefact/HsModule/Names.hs [hunk 1]
```diff
@@ -164,7 +164,7 @@ moduleOf ident m0 = case parts of
     -- We'd prefer to use `Foreign.Ptr` because it is a stable and
     -- compiler-agnostic interface in contrast to `GHC.Ptr`. However,
     -- `Foreign.Ptr` does not export the constructor of `Ptr`, which we need.
-    ["GHC", "Ptr"]                   -> HsImportModule "GHC.Ptr"   (Just "F")
+    ["GHC", "Ptr"]                   -> HsImportModule "GHC.Ptr"   (Just "Ptr")
```
Comment (TravisCardwell) [inline hs-bindgen/src-internal/HsBindgen/Backend/Artefact/HsModule/Names.hs:167]: FWIW, I think that we should use `Nothing` instead of `Just "Ptr"`, so that uses are qualified with `GHC.Ptr`.

IMHO, aliases should be used sparingly and conservatively.  Conflicts are indication that they should not be used.

Comment (dschrempf) [reply hs-bindgen/src-internal/HsBindgen/Backend/Artefact/HsModule/Names.hs:167]: OK, that's a good idea. I think the generated code should use fully qualified names anyways. (Given that we don't have to edit the code by hand, which we should not).

I will add this to #1061.
