### PR TITLE
Fix alignment of types in TH

### LINKED ISSUE #1422: Fix alignment of types of foreign imports in TH fixtures
We noticed that the types of the foreign imports in the Template Haskell fixutres (`th.txt` files) are aligned in a weird way:

```haskell
foreign import ccall safe "hs_bindgen_1c811bfb80de8f77" hs_bindgen_1c811bfb80de8f77 :: CDouble ->
                                                                                       CDouble
```

I briefly tried to change that, but the functions are quite complicated. I think we use `TH.ppr_dec`, which is a library function? Armando knows his way around there.

We want the output to look like

```haskell
foreign import ccall safe "hs_bindgen_1c811bfb80de8f77" hs_bindgen_1c811bfb80de8f77 ::
     FC.CDouble
  -> FC.CDouble
```

### PR DESCRIPTION
**Pull request by bolt12**
This closes #1422

### CODE REVIEW

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/TH.hs [hunk 1]
```diff
@@ -213,6 +213,17 @@ prettyWithDocumentationMap isTop docMap dec =
...
+    TH.ForeignD (TH.ImportF callconv safety impent name typ) ->
+            formatDecDoc docMap dec
+      TH.$$ TH.hsep [ TH.text "foreign import"
+                    , pprCallconv callconv
+                    , pprSafety safety
+                    , TH.text (show impent)
+                    , TH.ppr name
+                    , TH.text "::"
+                    ]
+      TH.$$ TH.nest nestDepth (thCompatPprType typ)
```
Comment (bolt12) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/TH.hs:228]: add a comment describing why we overwrite the default renderer
