### PR TITLE
Make bindings compile even when `NoFieldSelectors` is enabled globally

### LINKED ISSUE #1657: Generated code fails to build if `NoFieldSelectors` is enabled globally
We should probably include the inverse (`NoNoFieldSelectors`? `FieldSelectors?`) as required language extensions (unless using `--enable-record-dot`).

### PR DESCRIPTION
**Pull request by jorisdral**
Resolves #1657

Rather than using field selectors, we use `getField` calls unconditionally. Generated bindings should then compile regardless of whether `NoFieldSelectors` is enabled.

### CODE REVIEW

File: hs-bindgen/src-internal/HsBindgen/Backend/SHs/Translation.hs [hunk 1]
```diff
@@ -647,17 +646,12 @@ translateCEnumInstance struct fTyp vMap isSequential fieldNamingStrategy mbComme
...
+
     fromCEnumE :: ClosedExpr
-    fromCEnumE =
-      case fieldNamingStrategy of
-        OmitFieldPrefixes ->
-          eBindgenGlobal HasField_getField `ETypeApp` translateType (Hs.HsStrLit "unwrap")
-        AddFieldPrefixes ->
-          EFree fname
+    fromCEnumE = ELam "x" $
+      EApp (eBindgenGlobal HasField_getField `ETypeApp` translateType (Hs.HsStrLit fnameStr)) (EBound IZ)
```
Comment (jorisdral) [inline hs-bindgen/src-internal/HsBindgen/Backend/SHs/Translation.hs]:
```suggestion
    fromCEnumE = eBindgenGlobal HasField_getField `ETypeApp` translateType (Hs.HsStrLit fnameStr)
