### PR TITLE
Fix TH duplicate symbols & Compile TH fixtures 

### LINKED ISSUE #1587: Our TH fixtures contain duplicate symbols
Arbitrary example: `fixtures/attributes/asm/th.txt` (modulo merging #1586) contains C wrappers

```c
signed int hs_bindgen_369133049bfc1e73 (signed int arg1, signed int arg2) {
  return asm_labeled_function(arg1, arg2);
}
signed int hs_bindgen_3ad6c287a2386382 (signed int arg1, signed int arg2) {
  return asm_labeled_function(arg1, arg2);
}
```

along with Haskell imports

```hs
foreign import ccall safe "hs_bindgen_369133049bfc1e73" 
  hs_bindgen_369133049bfc1e73_base :: CInt -> CInt -> IO CInt
foreign import ccall unsafe "hs_bindgen_3ad6c287a2386382" 
  hs_bindgen_3ad6c287a2386382_base :: CInt -> CInt -> IO CInt
```

So far so good (though the duplication is unfortunate; see https://github.com/well-typed/hs-bindgen/issues/1344). However, we then define

```hs
asm_labeled_function :: CInt -> CInt -> IO CInt
asm_labeled_function = hs_bindgen_369133049bfc1e73

asm_labeled_function :: CInt -> CInt -> IO CInt
asm_labeled_function = hs_bindgen_3ad6c287a2386382

asm_labeled_function :: FunPtr (CInt -> CInt -> IO CInt)
asm_labeled_function = unsafePerformIO hs_bindgen_4f7c4fceed28f171
```

This is wrong; we should instead use @dschrempf 's category selection infrastructure to rename or to select.

### PR DESCRIPTION
**Pull request by bolt12**
This closes #1587 and #1588

### CODE REVIEW

File: hs-bindgen/examples/golden/types/stdlib/stdlib_insts.h [hunk 1]
```diff
@@ -48,8 +50,10 @@ typedef wint_t    stdlib_CWintT;
 typedef mbstate_t stdlib_CMbstateT;
 typedef wctrans_t stdlib_CWctransT;
 typedef wctype_t  stdlib_CWctypeT;
+#if __has_include(<uchar.h>)
```
Comment (bolt12) [inline hs-bindgen/examples/golden/types/stdlib/stdlib_insts.h]: double check the need for this.

File: hs-bindgen/test/common/Test/Common/HsBindgen/TestCase/All.hs
Comment (bolt12) [inline hs-bindgen/test/common/Test/Common/HsBindgen/TestCase/All.hs:1]: no need to have this anymore because the TH compiling test suite is not separate

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+{-------------------------------------------------------------------------------
+  Platform-specific skips
+-------------------------------------------------------------------------------}
+
+-- | Tests that fail on Windows due to platform-specific issues
+--
+-- Each entry pairs a test name with its specific skip reason.
+--
+windowsSpecificFailures :: [(String, String)]
+windowsSpecificFailures =
```
Comment (bolt12) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs]: Double check if this is a duplicated list of the compile-fixtures script. And if so, add references to each files

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+      ]
+      = THSkip "Complex configuration (program slicing, disabled stdlib)"
+  -- Empty output fixtures
+  | s.name `elem` emptyOutputFixtures
+      = THSkip "Empty fixture (no bindings generated)"
+  -- Variant tests (name contains a period followed by a number)
+  | isVariantTest s.name
+      = THSkip "Variant test (only base test compiled)"
+  | otherwise
+      = THCompile
```
Comment (bolt12) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs]: Double check if this is a duplicated list of the compile-fixtures script. And if so, add references to each files

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+  , "program-analysis/selection_foo"
+  , "program-analysis/selection_merge_traces"
+  , "program-analysis/selection_omit_prescriptive"
+  , "program-analysis/selection_squash_typedef"
+  , "types/special/long_double"
+  , "types/structs/implicit_fields_struct"
+  , "types/structs/unnamed-struct"
+  , "types/unions/implicit_fields_union"
+  , "types/typedefs/typenames"
+  ]
```
Comment (bolt12) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/THFixtures/TestCases.hs]: Double check if this is a duplicated list of the compile-fixtures script. And if so, add references to each files

File: .github/actions/setup-llvm/action.yml [hunk 5]
```diff
@@ -35,6 +35,9 @@ runs:
       export SDKROOT=$(xcrun --show-sdk-path --sdk macosx)
       echo $SDKROOT
       echo "SDKROOT=$SDKROOT" >> "$GITHUB_ENV"
+      # Standalone LLVM does not automatically use SDKROOT to find system
+      # headers (e.g. uchar.h). Pass -isysroot so libclang can locate them.
```
Comment (bolt12) [inline .github/actions/setup-llvm/action.yml]:
```suggestion
      # headers. Pass -isysroot so libclang can locate them.
```

**Comment by bolt12** [comment]
Investigate why compiling the golden tests fixtures from preprocess mode work on MacOS and Windows with linux musl headers but do not work when compiling TH.

File: .github/actions/setup-llvm/action.yml [hunk 6]
```diff
@@ -29,12 +29,15 @@ runs:
...
     run: |
-      echo "LLVM_CONFIG=$LLVM_PATH/bin/llvm-config" | tee -a "$GITHUB_ENV"
-      echo "LIBCLANG_PATH=$LLVM_PATH/lib" | tee -a "$GITHUB_ENV"
-      # hs-bindgen automatically sets SDKROOT, but we still need to to build
-      # shared libraries with Clang.
-      SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
+      echo "LLVM_CONFIG=$LLVM_PATH/bin/llvm-config" >> "$GITHUB_ENV"
+      echo "LIBCLANG_PATH=$LLVM_PATH/lib/" >> "$GITHUB_ENV"
+      # https://stackoverflow.com/questions/63342521/clang-on-macos-having-problems-with-its-includes
+      export SDKROOT=$(xcrun --show-sdk-path --sdk macosx)
```
Comment (edsko) [inline .github/actions/setup-llvm/action.yml]: This should not be necessary anymore as of https://github.com/well-typed/hs-bindgen/pull/1716 .

File: hs-bindgen/fixtures/manual/enable_record_dot/th.txt [hunk 7]
```diff
@@ -686,7 +686,7 @@ __defined at:__ @manual\/enable_record_dot.h 66:15@
 __exported by:__ @manual\/enable_record_dot.h@
 -}
 newtype RunDriver_Aux
-    = RunDriver_Aux {unwrap :: (Ptr Driver -> IO CInt)}
+    = RunDriver_Aux {unwrapRunDriver_Aux :: (Ptr Driver -> IO CInt)}
```
Comment (edsko) [inline hs-bindgen/fixtures/manual/enable_record_dot/th.txt]: This doesn't look right? Looks like record dot is no longer enabled here?

File: hs-bindgen/fixtures/functions/simple_func/th.txt [hunk 8]
```diff
@@ -105,20 +105,28 @@ foreign import ccall safe "hs_bindgen_1c811bfb80de8f77" hs_bindgen_1c811bfb80de8
 hs_bindgen_1c811bfb80de8f77 :: CDouble -> CDouble
 -- __unique:__ @test_functionssimple_func_Example_Safe_erf@
 hs_bindgen_1c811bfb80de8f77 = fromFFIType hs_bindgen_1c811bfb80de8f77_base
-{-| __C declaration:__ @erf@
+{-|
 
-    __defined at:__ @functions\/simple_func.h 1:8@
+  Marked @__attribute((const))__@
```
Comment (edsko) [inline hs-bindgen/fixtures/functions/simple_func/th.txt:110]: Where is this difference coming from?

File: hs-bindgen/fixtures/functions/simple_func.1.rename/th.txt [hunk 9]
```diff
@@ -1,5 +1,63 @@
 -- addDependentFile examples/golden/functions/simple_func.h
 -- #include <functions/simple_func.h>
+-- double hs_bindgen_52a0bfa9acc31e7d (
```
Comment (edsko) [inline hs-bindgen/fixtures/functions/simple_func.1.rename/th.txt]: Why do we have all this new code here?

File: .github/actions/setup-llvm/action.yml (hunk 6 above)
Comment (bolt12) [reply .github/actions/setup-llvm/action.yml]: This file is unchanged from `main` (`git diff main -- .github/actions/setup-llvm/action.yml` is empty). The diff you're seeing is a per-commit artifact — the PR diff doesn't include this file.

File: hs-bindgen/fixtures/manual/enable_record_dot/th.txt (hunk 7 above)
Comment (bolt12) [reply hs-bindgen/fixtures/manual/enable_record_dot/th.txt]: Good catch — this was a bug. The TH test was overriding `onBackend` with `const (getTestThBackendConfig ...)`, which discarded the test case's `fieldNamingStrategy = EnableRecordDot` setting.

File: hs-bindgen/fixtures/functions/simple_func/th.txt (hunk 8 above)
Comment (bolt12) [reply hs-bindgen/fixtures/functions/simple_func/th.txt:110]: This diffference comes from the fact that now the functions have unique names and our `putDoc` function calls were overwriting each other or some weird interaction was happening.

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Resources.hs [hunk 10]
```diff
@@ -111,4 +116,33 @@ getTestDefaultBackendConfig testName pathStyle = def{
...
+      -- Use all categories with suffixes to avoid duplicate symbols in TH output.
+      -- See https://github.com/well-typed/hs-bindgen/issues/1587
+    , categoryChoice = ByCategory {
+          cType   = IncludeTypeCategory
+        , cSafe   = IncludeTermCategory def
+        , cUnsafe = IncludeTermCategory def
+        , cFunPtr = IncludeTermCategory def
+        , cGlobal = IncludeTermCategory def
+        }
+    }
```
Comment (bolt12) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/Resources.hs]:
```suggestion
```
