### PR TITLE
Test infrastructure

### LINKED ISSUE #722: Infrastructure for tests with expected failures
At the moment, we create a fixture for `long_double` containing an error message.

Instead, we should collect traces and expect specific trace messages.

Also, we should separate working from failing examples.

Collected expected failing tests so far:
- `implicit_field_struct.h`
- `long_double.h`

Collected other tests so far (not golden, not failing):
- `comments.h`
-  `examples/invalid_standard_types.h`
- `standard_types.h`
- `test_01.h`
- `test_02.h`

### PR DESCRIPTION
**Pull request by dschrempf**
- Separate examples into golden/golden-norust/failing and others

- Add `expectTrace`, a function that tests for specific traces

Closes #722 

Does not yet remove the `long_double` golden test (separate issue #726).

### CODE REVIEW

**Comment by dschrempf** [comment]
For now, we have the following categories:

```
  failing
  golden
  golden-norust
```

And the following tests at top level (examples/):

```
  comments.h
  invalid_standard_types.h
  standard_types.h
  test_01.h
  test_02.h
```

File: hs-bindgen/test/internal/test-internal.hs [hunk 1]
```diff
@@ -195,16 +212,26 @@ tests packageRoot getAnsiColor getRustBindgen =
...
           result <- try $ do
             decls <- Pipeline.translateCHeader "testmodule" opts headerIncludePath
-
-            -- TODO: PP.render should add trailing '\n' itself.
-            evaluate $ force $ Pipeline.preprocessPure ppOpts decls ++ "\n"
+            evaluate $ force $ Pipeline.preprocessPure ppOpts decls
 
           case result of
-            Right result' -> fail $
+            Right result' -> panicIO $
```
Comment (dschrempf) [inline hs-bindgen/test/internal/test-internal.hs]: This should not be a panicIO.
