### PR TITLE
Invoke hs-bindgen once per PP golden test

### LINKED ISSUE #1787: Single invocation of bindgen per golden test
If hs-bindgen stumbles over a test case (panic, say) we currently get that exception `n` times for each golden test (one per category?). It would be better if we had a _single_ invocation that generates _all_ golden tests.

I think this is a step towards @jorisdral 's vision in https://github.com/well-typed/hs-bindgen/issues/1495, but I think won't get us _quite_ there yet (though Joris can correct me); in particular, it does not add anything clever for binding specs, or deal with multiple invocations of `hs-bindgen` for _different_ header files. It is merely about generating all _categories_ for a _single_ header at once.

### PR DESCRIPTION
**Pull request by bolt12**
This closes #1787

### CODE REVIEW

**Comment by edsko** [comment]
@dschrempf could I ask you to review this? @bolt12 feel free to merge once Dominik gives the green light.

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs [hunk 1]
```diff
@@ -24,51 +28,71 @@ import Test.HsBindgen.Resources
...
-            <- runTestHsBindgenSuccess report getTestResources test artefacts
+          result <- getResult
+          case result of
+            Left e
+              -- The primary sub-test re-throws the original exception so that
+              -- tasty displays the full error. The other sub-tests just
+              -- reference it, avoiding redundant error output.
+              | bc == NonEmpty.head allCategories -> throwIO e
+              | otherwise   ->
+                assertFailure "hs-bindgen failed (see CType for details)"
```
Comment (dschrempf) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs]: What happens if we only test for a Term category (i.e., not for CType)?

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs [hunk 2]
```diff
@@ -24,51 +28,71 @@ import Test.HsBindgen.Resources
...
+              qualifiedStyle = view #qualifiedStyle backendCfg
+            }
+          fns = view #fieldNamingStrategy backendCfg
+          artefacts = (,)
+                    <$> FinalModuleBaseName
+                    <*> getBindingsMultiple fns mrc
+      (baseName, output) <-
+        runTestHsBindgenSuccess collectTrace getTestResources test artefacts
+      msgs <- reverse <$> readIORef traceMessages
+      pure (baseName, msgs, output)
```
Comment (dschrempf) [inline hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs]: This seems like some unnecessary code duplication (but I may be wrong). Did you have a look at `runTestHsBindgen`, it returns an `Eiter` already, and doesn't expect a success like `runTestHsBindgenSuccess`.

I think you do this because you need the trace messages, right?

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs (hunk 1 above)
Comment (bolt12) [reply hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs]: Good point, I should use the show instance for `bc`

File: hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs (hunk 2 above)
Comment (bolt12) [reply hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs]: Yes that's right, I will look into that! I might have overlooked something!

Comment (bolt12) [reply hs-bindgen/test/hs-bindgen/Test/HsBindgen/Golden/Check/PP.hs]: addressed! Could you take a look now?
