### PR TITLE
Fix output locations format to avoid mangling STDIO

### LINKED ISSUE #1270: Literate mode mangles `STDIO`
We have observed source locations strings for anonymous declarations with error test in them.  For example, we see `/usr/include/bits/types/struct_timespec.h:7:0: error: 1` instead of `/usr/include/bits/types/struct_timespec.h:7:1`.  This only happens in some situations, notably when running `cabal run test-pp`.

While I do not fully understand why this is happening yet, debugging indicates that the way that Cabal runs the literate preprocessor causes `STDIO` to be mangled.

### PR DESCRIPTION
**Pull request by bolt12**
Fix #1270 

I confirmed with @TravisCardwell reproducible that the issue is fixed! Thank you!

### CODE REVIEW

File: hs-bindgen/src-internal/HsBindgen/Backend/HsModule/Render.hs [hunk 1]
```diff
@@ -224,11 +224,9 @@ instance Pretty CommentKind where
...
 prettyHashIncludeArgLoc :: C.HeaderInfo -> SingleLoc -> CtxDoc
 prettyHashIncludeArgLoc info loc = PP.string $
-    List.intercalate ":" [
-        escapePaths info.includeArg.path
-      , show (singleLocLine loc)
-      , show (singleLocColumn loc)
-      ]
+    -- Use space instead of first colon to avoid GHC literate preprocessor mangling
+    escapePaths info.includeArg.path ++ " "
+      ++ show (singleLocLine loc) ++ ":" ++ show (singleLocColumn loc)
```
Comment (bolt12) [inline hs-bindgen/src-internal/HsBindgen/Backend/HsModule/Render.hs:229]: This also needs a similar change in libclang in the function `prettySingleLoc`!

**Comment by TravisCardwell** [comment]
This PR did not update the `source-repository-package` for the `libclang` repo, so it did not include the source location change made there and therefore still had the issue.

To test, I added the following to `test_01.h`:

```c
struct mangle_test {
  struct { long double ld; } foo;
};
```

The issue was reproduced when building (`cabal build all`):

```
[Warning] [HsBindgen] [select-parse-delayed] 'struct mangle_test'  at  "examples/test_01.h:415:0: error:
    8"
      Could not select declaration:
        Parse failure:
          No bindings generated: Unsupported long double
```

We cannot simply update the `source-repository-package`, however, because the `libclang` repo has a commit for #1450, which is not ready yet.  We attempted to always get the C standard being used from `libclang`, but this does not work on Windows when using MSVC targets because Microsoft does not follow standards.  We need to distinguish the non-standard Microsoft C case.  I reverted the problematic `libclang` commit so that we can update the `source-repository-package`.  That commit can be cherry-picked when we work on #1450, adding a new commit to distinguish Microsoft C.

With the `source-repository-package` updated, the issue is indeed resolved:

```
Template Haskell error: [Warning] [HsBindgen] [select-parse-delayed] 'struct mangle_test'  at  "./examples/test_01.h 415:8"
  Could not select declaration:
    Parse failure:
      No bindings generated: Unsupported long double
```

I see that this PR was not merged just because of an intermittent CI issue.  I will go ahead and merge now.

**Comment by TravisCardwell** [comment]
CI for macOS is still failing.

```
 Warning: cannot determine version of /opt/homebrew/bin/git :
""
dyld[85653]: Symbol not found: _libiconv
  Referenced from: <E1ACFC9D-3501-35D5-A81E-9C76DD619092> /opt/homebrew/Cellar/git/2.52.0_1/bin/git
  Expected in:     <B27D3B05-B1FB-3728-B61A-FAA07DF2FCFD> /usr/lib/libiconv.2.dylib
/Users/runner/work/_temp/d1aedc74-e808-4fb3-b939-b2365cf056ae.sh: line 1: 85644 Abort trap: 6           cabal build all --dry-run
Error: Process completed with exit code 134.
```

Perhaps this was triggered by an update to the runner image and is not an intermittent issue.
