### PR TITLE
Compile fixtures

### LINKED ISSUE #1070: Test compilation of fixtures
I do think we have a ticket for testing compilation of fixtures, but I could not find it.

_We should compile all generated fixtures in our CI/CD pipeline._

I know, the pipeline is already taking too long. However, I think it is important that we produce working code, and that we do not introduce regressions, that are otherwise invisible to us.

For example, I have a branch https://github.com/well-typed/hs-bindgen/tree/dom/test-fixture-compilation with a  relatively simple [compilation script](https://github.com/well-typed/hs-bindgen/blob/dom/test-fixture-compilation/hs-bindgen/fixtures/compile).

Last update: 2025-10-01.

This script now reports a total of 9 failures (which is a big improvement to earlier times):

```
Compilation of bool_c23.pp.hs failed. (C-phase)
Compilation of decls_in_signature.pp.hs failed. (C-phase)
Compilation of fun_attributes.pp.hs failed. (C-phase)
Compilation of macro_strings.pp.hs failed. (GHC-phase)
Compilation of iterator.pp.hs failed. (C-phase)
Compilation of program_slicing_simple.pp.hs failed. (GHC-phase)
Compilation of redeclaration.pp.hs failed. (GHC-phase)
Compilation of typenames.pp.hs failed. (GHC-phase)
Compilation of reparse.pp.hs failed. (GHC-phase)

```

We can, for example, do this compilation only for one combination of `(CompilerVersion,OS,LLVMVersion)`.

### PR DESCRIPTION
**Pull request by bolt12**
This PR closes #1070.

We only ignore 4 fixtures:

- iterator.pp.hs: Makes use of Apple block extension which would require clang (see #913)
- decls_in_signature.pp.hs: Unusable struct (see #1128)
- redeclaration.pp.hs: Same as typenames.pp.hs
- typenames.pp.hs: hs-bindgen namespace possible bug/feature

And fixed 6 fixtures that weren't compiling.

### CODE REVIEW

**Comment by jorisdral** [comment]
Quick drive-by comment: the script only picks up fixtures that are in the `hs-bindgen/fixtures` directory, but not any of it's sub-directories, like `hs-bindgen/fixtures/manual`. Maybe the script should search through the folders recursively

**Comment by bolt12** [comment]
@jorisdral thanks! Good point! I'll fix it!

File: hs-bindgen/src-internal/HsBindgen/Backend/HsModule/Names.hs [hunk 1]
```diff
@@ -204,6 +204,7 @@ resolveGlobal = \case
     Applicative_seq               -> importU '(<*>)
     Monad_return                  -> importU 'return
     Monad_seq                     -> importU '(>>)
+    Maybe_type                    -> ResolvedName "Maybe(..)" IdentifierName (Just (UnqualifiedHsImport iPrelude))
```
Comment (bolt12) [inline hs-bindgen/src-internal/HsBindgen/Backend/HsModule/Names.hs]: Use Prelude.Just and Prelude.Nothing
